# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Team.create!([
  {team: "Atlanta Hawks", points_allowed: 116, points_scored: 108, avg_age: 26 },
  {team: "Boston Celtics", points_allowed: 98, points_scored: 102 , avg_age: 24},
  {team: "Brooklyn Nets", points_allowed: 112, points_scored: 108 , avg_age: 25},
  {team: "Charlotte Hornets", points_allowed: 110, points_scored: 116 , avg_age: 25},
  {team: "Chicago Bulls", points_allowed: 118, points_scored: 110 , avg_age: 24},
  {team: "Cleveland Cavaliers", points_allowed: 118, points_scored: 110 , avg_age: 30},
  {team: "Dallas Mavericks", points_allowed: 117, points_scored: 111 , avg_age: 27},
  {team: "Denver Nuggets", points_allowed: 105, points_scored: 113 , avg_age: 25},
  {team: "Detroit Pistons", points_allowed: 113, points_scored: 111 , avg_age: 26},
  {team: "Golden State Warriors", points_allowed: 112 , points_scored: 125 , avg_age: 28},
  {team: "Houston Rockets", points_allowed: 116 , points_scored: 106 , avg_age: 28},
  {team: "Indiana Pacers", points_allowed: 103, points_scored: 109 , avg_age: 25},
  {team: "Los Angeles Clippers", points_allowed: 110, points_scored: 116 , avg_age: 26},
  {team: "Los Angeles Lakers", points_allowed: 121, points_scored: 121 , avg_age: 26},
  {team: "Memphis Grizzlies", points_allowed: 100, points_scored: 104 , avg_age: 24},
  {team: "Miami Heat", points_allowed: 111, points_scored: 112 , avg_age: 25},
  {team: "Milwaukee Bucks", points_allowed: 104, points_scored: 120 , avg_age: 26},
  {team: "Minnesota Timberwolves", points_allowed: 119, points_scored: 116 , avg_age: 27},
  {team: "New Orleans Pelicans", points_allowed: 121, points_scored: 122 , avg_age: 27},
  {team: "New York Knicks", points_allowed: 110, points_scored: 106 , avg_age: 26},
  {team: "Oklahoma City Thunder", points_allowed: 111, points_scored: 109 , avg_age: 27},
  {team: "Orlando Magic", points_allowed: 111, points_scored: 101 , avg_age: 25},
  {team: "Philadelphia 76ers", points_allowed: 114, points_scored: 113 , avg_age: 24},
  {team: "Phoenix Suns", points_allowed: 118, points_scored: 103 , avg_age: 24},
  {team: "Portland Trailblazers", points_allowed: 109, points_scored: 117 , avg_age: 25},
  {team: "Sacramento Kings", points_allowed: 117, points_scored: 117 , avg_age: 25},
  {team: "San Antonio Spurs", points_allowed: 113, points_scored: 115 , avg_age: 28},
  {team: "Toronto Raptors", points_allowed: 109, points_scored: 117 , avg_age: 25},
  {team: "Utah Jazz", points_allowed: 109, points_scored: 114 , avg_age: 26},
  {team: "Washington Wizards", points_allowed: 122, points_scored: 112 , avg_age: 26}

])


Player.create!([
  {name: "James Harden" , position: "Shooting Guard", age: 29, points: 32, team: "Houston Rockets"},
  {name: "Kevin Durant", position: "Small Forward", age: 30, points: 29, team: "Golden State Warriors"},
  {name: "Stephen Curry", position: "Point Guard", age: 30, points: 29, team: "Golden State Warriors"},
  {name: "Anthony Davis", position: "Power Forward", age: 25, points: 28, team: "New Orleans Pelicans"},
  {name: "Damian Lillard", position: "Point Guard", age: 28, points: 27, team: "Portland Trailblazers"},
  {name: "Kawhi Leonard", position: "Small Forward", age: 27, points: 27, team: "Toronto Raptors"},
  {name: "Joel Embiid", position: "Center", age: 24, points: 27, team: "Philadelphia 76ers"},
  {name: "Giannis Antetokounmpo", position: "Small Forward", age: 24, points: 26, team: "Milwaukee Bucks"},
  {name: "Paul George", position: "Small Forward", age: 28, points: 26, team: "Oklahoma Thunder"},
  {name: "Devin Booker", position: "Shooting Guard", age: 22, points: 25, team: "Phoenix Suns"},
  {name: "Blake Griffin", position: "Power Forward", age: 29, points: 25, team: "Detroit Pistons"},
  {name: "Kemba Walker", position: "Point Guard", age: 28, points: 25, team: "Charlotte Hornets"},
  {name: "Zach Lavine", position: "Shooting Guard", age: 23, points: 23, team: "Chicago Bulls"},
  {name: "Bradley Beal", position: "Shooting Guard", age: 25, points: 24, team: "Washington Wizards"},
  {name: "Demar Derozan", position: "Shooting Guard", age: 29, points: 23, team: "San Antonio Spurs"},
  {name: "Kyrie Irving", position: "Point Guard", age: 26, points: 23, team: "Boston Celtics"},
  {name: "Tobias Harris", position: "Small Forward", age: 26, points: 22, team: "Los Angeles Clippers"},
  {name: "Klay Thompson", position: "Shooting Guard", age: 28, points: 21, team: "Golden State Warriors"},
  {name: "CJ McCollum", position: "Shooting Guard", age: 27, points: 21, team: "Portland Trailblazers"},
  {name: "Jrue Holiday", position: "Point Guard", age: 28, points: 21, team: "New Orleans Pelicans"},
  {name: "Karl-Anthony Towns", position: "Center", age: 23, points: 21, team: "Minnesota Timberwolves"},
  {name: "Tim Hardaway Jr", position: "Shooting Guard", age: 26, points: 21, team: "New York Knicks"},
  {name: "John Wall", position: "Point Guard", age: 28, points: 21, team: "Washington Wizards"},
  {name: "Mike Conley", position: "Point Guard", age: 31, points: 20, team: "Memphis Grizzlies"},
  {name: "Russell Westbrook", position: "Point Guard", age: 30, points: 20, team: "Oklahoma City Thunder"},
  {name: "Donovan Mitchell", position: "Point Guard", age: 22, points: 20, team: "Utah Jazz"},
  {name: "Nikola Vucevic", position: "Power Forward", age: 28, points: 20, team: "Orlando Magic"},
  {name: "Buddy Hield", position: "Shooting Guard", age: 26, points: 20, team: "Sacramento Kings"},
  {name: "Victor Oladipo", position: "Point Guard", age: 26, points: 20, team: "Indiana Pacers"},
  {name: "Jimmy Butler", position: "Shooting Guard", age: 29, points: 20, team: "Philadelphia 76ers"},
  {name: "Danilo Gallinari", position: "Small Forward", age: 30, points: 20, team: "Los Angeles Clippers"},
  {name: "Julius Randle", position: "Power Forward", age: 24, points: 19, team: "New Orleans Pelicans"},
  {name: "Luka Doncic", position: "Point Guard", age: 19, points: 19, team: "Dallas Mavericks"},
  {name: "Kevin Love", position: "Power Forward", age: 30, points: 19, team: "Cleveland Cavaliers"},
  {name: "LaMarcus Aldridge", position: "Power Forward", age: 33, points: 19, team: "San Antonio Spurs"},
  {name: "Derrick Rose", position: "Point Guard", age: 30, points: 19, team: "Minnesota Timberwolves"},
  {name: "John Collins", position: "Center", age: 21, points: 19, team: "Atlanta Hawks"},
  {name: "T.J. Warren", position: "Small Forward", age: 25, points: 19, team: "Phoenix Suns"},
  {name: "Josh Richardson", position: "Small Forward", age: 25, points: 19, team: "Miami Heat"},
  {name: "Caris LeVert", position: "Small Forward", age: 24, points: 18, team: "Brooklyn Nets"},
  {name: "Harrison Barnes", position: "Small Forward", age: 26, points: 18, team: "Dallas Mavericks"},
  {name: "Kyle Kuzma", position: "Power Forward", age: 23, points: 18, team: "Los Angeles Lakers"},
  {name: "Spencer Dinwiddie", position: "Point Guard", age: 25, points: 18, team: "Brooklyn Nets"},
  {name: "De'Aaron Fox", position: "Point Guard", age: 21, points: 18, team: "Sacramento Kings"},
  {name: "JJ Redick", position: "Shooting Guard", age: 34, points: 18, team: "Philadelphia 76ers"},
  {name: "Nikola Jokic", position: "Center", age: 23, points: 18, team: "Denver Nuggets"},
  {name: "Andre Drummond", position: "Center", age: 25, points: 18, team: "Detroit Pistons"},
  {name: "Lou Williams", position: "Shooting Guard", age: 32, points: 18, team: "Los Angeles Clippers"},
  {name: "D'Angelo Russell", position: "Point Guard", age: 22, points: 18, team: "Brooklyn Nets"}


])